autoload -Uz compinit
compinit -u

zstyle ':completion:*:messages' format 'Message: %d'

# Useful for debugging: shows when completion functions generate no suggestions.
# zstyle ':completion:*:warnings' format 'Warning: %d'

PROMPT='PROMPT-LINE %/ > '
