#! /usr/bin/env bash

set -euo pipefail

invocation_time=$(date -u +"%Y-%m-%dT%H:%M:%S%Z")

cat <<EOF > "/tmp/batect-zsh-completion-tests/$invocation_time.txt"
BATECT_COMPLETION_PROXY_VERSION is $BATECT_COMPLETION_PROXY_VERSION
BATECT_COMPLETION_PROXY_REGISTER_AS is $BATECT_COMPLETION_PROXY_REGISTER_AS
Arguments were: $@
EOF

cat <<EOF
$BATECT_COMPLETION_PROXY_REGISTER_AS() {
  local -a args
  args+=(
    '--do-thing'
    '--other-thing'
    '--other-stuff'
  )
  _arguments \$args[@] && return 0
  return 1
}
EOF
