#! /usr/bin/env bash

set -euo pipefail

# Unused in script - used by proxy script to determine version
VERSION="1.0.0"

invocation_time=$(date -u +"%Y-%m-%dT%H:%M:%S%Z")

cat <<EOF > "/tmp/batect-zsh-completion-tests/$invocation_time.txt"
BATECT_COMPLETION_PROXY_VERSION is $BATECT_COMPLETION_PROXY_VERSION
BATECT_COMPLETION_PROXY_REGISTER_AS is $BATECT_COMPLETION_PROXY_REGISTER_AS
BATECT_QUIET_DOWNLOAD is $BATECT_QUIET_DOWNLOAD
Arguments were: $@
EOF

cat <<EOF
_batect_completion_$BATECT_COMPLETION_PROXY_REGISTER_AS_echo_proxy_completion_path() {
  echo path-\$BATECT_COMPLETION_PROXY_WRAPPER_PATH-path
}

_batect_completion_$BATECT_COMPLETION_PROXY_REGISTER_AS() {
  integer ret=1
  local -a args
  args+=(
    '--do-thing',
    '--other-thing',
    '--third-thing',
    '--wrapper-script-path:string:_batect_completion_$BATECT_COMPLETION_PROXY_REGISTER_AS_echo_proxy_completion_path'
  )
  _arguments \$args[@] && ret=0
  return ret
}

compdef _batect_completion_$BATECT_COMPLETION_PROXY_REGISTER_AS $BATECT_COMPLETION_PROXY_REGISTER_AS
EOF
