#! /usr/bin/env bash

set -euo pipefail

# Unused in script - used by proxy script to determine version
VERSION="1.0.0"

invocation_time="$(date -u +"%Y-%m-%dT%H:%M:%S%Z")-$(uuidgen)"

cat <<EOF > "/tmp/batect-zsh-completion-tests/$invocation_time.txt"
BATECT_COMPLETION_PROXY_VERSION is $BATECT_COMPLETION_PROXY_VERSION
BATECT_COMPLETION_PROXY_REGISTER_AS is $BATECT_COMPLETION_PROXY_REGISTER_AS
BATECT_QUIET_DOWNLOAD is $BATECT_QUIET_DOWNLOAD
Arguments were: $@
EOF

cat <<EOF
_${BATECT_COMPLETION_PROXY_REGISTER_AS}_echo_proxy_completion_path() {
  local options
  options=(path-\${BATECT_COMPLETION_PROXY_WRAPPER_PATH}-path)
  _describe 'options' options
}

$BATECT_COMPLETION_PROXY_REGISTER_AS() {
  local -a args
  args+=(
    '--do-thing'
    '--other-thing'
    '--other-stuff'
    '--wrapper-script-path+:string:_${BATECT_COMPLETION_PROXY_REGISTER_AS}_echo_proxy_completion_path'
  )
  _arguments \$args[@] && return 0
  return 1
}
EOF
