name: Pipeline

on: [push, pull_request]

jobs:
  build:
    name: "Lint and Test"
    runs-on: ubuntu-latest
    env:
      TERM: xterm-256color
      BATECT_CACHE_TYPE: directory
      BATECT_ENABLE_TELEMETRY: true
      DOCKER_BUILDKIT: 1

    steps:
      - name: Check out code
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0

      - name: Fix tag reference (workaround for https://github.com/actions/checkout/issues/290)
        run: git fetch -f origin ${{ github.ref }}:${{ github.ref }}
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/') && github.repository == 'batect/batect-zsh-completion'

      - name: Validate Batect wrapper scripts
        uses: batect/batect-wrapper-validation-action@v0.4.0

      - name: Cache Batect
        uses: actions/cache@v3.0.6
        with:
          path: ~/.batect/cache
          key: batect-${{ hashFiles('batect') }}

      - name: Check formatting
        run: ./batect check-format

      - name: Lint code
        run: ./batect lint

      - name: Test
        run: ./batect test

      - name: Check release environment
        run: ./batect check-release-env

      - name: Validate release
        run: ./batect validate-release
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/') && github.repository == 'batect/batect-zsh-completion'
